package output

import (
	"fmt"

	"github.com/declaw-ai/cagecheck/internal/checks"
	"github.com/declaw-ai/cagecheck/internal/detect"
	"github.com/declaw-ai/cagecheck/internal/report"
)

func PrintMarkdown(report report.Report) {
	fmt.Printf("# cagecheck Report\n\n")
	fmt.Printf("**Version:** %s  \n", report.Version)
	fmt.Printf("**Timestamp:** %s  \n", report.Timestamp)
	fmt.Printf("**Environment:** %s  \n", detect.FormatEnvironment(report.Environment))
	fmt.Printf("**Isolation Boundary:** %s  \n\n", report.Environment.Boundary.String())

	fmt.Printf("## Escape Checklist\n\n")
	fmt.Printf("| Status | Check |\n")
	fmt.Printf("|--------|-------|\n")
	for _, item := range report.Checklist {
		fmt.Printf("| %s | %s |\n", item.Status.String(), item.Detail)
	}
	fmt.Println()

	fmt.Printf("## Detailed Findings\n\n")
	for _, cat := range report.Findings {
		hasFindings := false
		for _, r := range cat.Results {
			if r.Status == checks.Fail || r.Status == checks.Warn {
				hasFindings = true
				break
			}
		}
		if !hasFindings {
			continue
		}
		fmt.Printf("### %s\n\n", cat.Name)
		for _, r := range cat.Results {
			if r.Status != checks.Fail && r.Status != checks.Warn {
				continue
			}
			fmt.Printf("- **[%s]** %s\n", r.Severity.String(), r.Detail)
		}
		fmt.Println()
	}

	fmt.Printf("---\n")
	fmt.Printf("*Generated by [cagecheck](https://github.com/declaw-ai/cagecheck)*\n")
}
